# -*- coding: utf-8 -*-
"""Estagio_Target_RP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JJq7IMQgB3Dzzu-a6iPbUL-G1J3ZKUF
"""

#Exercício 5

#etapa 1:
#Acendendo os interruptores A e B e indo a sala 1.

#etapa 2:
#Trocando a posição dos interruptores B e C (o B que estava acesso será apagado e os interruptores acessos serão os A e C) e indo a sala 2.

#Sabendo disso, caso a luz esteja apagada ao final da etapa um, ao visitar a sala 2 na etapa 2 é possível descobrir que:
#A sala 1 é controlada pelo interruptor C.
#Se a sala 2 estiver acesa, o interruptor que a controla é o A. Se a sala 2 estiver apagada é o B.
#Logo, a sala 3 é controlada pelo interruptor que sobrou.

#Caso a luz esteja acessa ao final da etapa 1, ao visitar a sala 2 na etapa 2 é possível descobrir que:
#A sala 1 é controlada pelo interruptor A ou B.
#Se a sala 2 estiver apagada, o interruptor que a controla é o B. Como a sala 1 estava acessa, seu interruptor é o A, sobrando o interruptor C para a sala 3.
#Se a sala 2 estiver acesa, como o interruptor B foi desligado, a sala 1 é controlada pelo interruptor B e sala 2 pelo A, sobrando o C para a sala 3.