# -*- coding: utf-8 -*-
"""Estagio_Target_RP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JJq7IMQgB3Dzzu-a6iPbUL-G1J3ZKUF
"""

#Exercício 3

INDICE = 12
SOMA = 0
K = 1

while K < INDICE:
    K = K + 1
    SOMA = SOMA + K

print(SOMA)