# -*- coding: utf-8 -*-
"""Estagio_Target_RP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JJq7IMQgB3Dzzu-a6iPbUL-G1J3ZKUF
"""

#Exercício 2

string_normal = input("Digite uma string: ")
qt_letra_a = 0
indice = 0

while indice < len(string_normal):
  if string_normal[indice] == 'a':
    qt_letra_a += 1
  indice += 1

print(f"A quantidade de letras 'a' na string é: {qt_letra_a}")