# -*- coding: utf-8 -*-
"""Estagio_Target_RP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JJq7IMQgB3Dzzu-a6iPbUL-G1J3ZKUF
"""

#Exercício 1

while True:
    valor_informado = input("Digite um valor inteiro (ou 'cancelar' para sair): ")

    if valor_informado.lower() == 'cancelar':
        print("Operação cancelada pelo usuário.")
        break

    try:
        numero_informado = int(valor_informado)
        seq_fibonacci, auxiliar_1, auxiliar_2 = 0, 0, 1
        while auxiliar_1 <= numero_informado:
            if auxiliar_1 == numero_informado:
                seq_fibonaccci = 1
                break
            auxiliar_1, auxiliar_2 = auxiliar_2, auxiliar_1 + auxiliar_2

        if seq_fibonacci == 1:
            print(f"O número {numero_informado} pertence à sequência de Fibonacci.")
        else:
            print(f"O número {numero_informado} não pertence à sequência de Fibonacci.")
        break
    except ValueError:
        print("O valor informado não é um número inteiro.")